[package]
name = "pymute"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["cargo", "derive"]}
cp_r = "0.5.1"
glob = "0.3.1"
rayon = "1.10.0"
tempfile = "3.10.1"
